blank_issues_enabled: false
contact_links:
  - name: Questions & Discussion
    url: https://github.com/forever-healthy/AI4L/discussions
    about: For questions, ideas, feedback, or sharing evidence reviews you've created.
